// SPDX-License-Identifier: AGPL-3.0-or-later
package cc.wujm.ashlar.render;

import cc.wujm.ashlar.engine.Region;
import cc.wujm.ashlar.engine.RegionData;
import com.google.gson.JsonParser;
import org.junit.jupiter.api.Test;
import java.util.Arrays;
import java.util.List;
import static org.junit.jupiter.api.Assertions.*;

class ShapeRendererTest {
    private static RegionData data(String state){return new RegionData(new Region(0,0,0,0,0,0),List.of(state),new int[]{0},new int[]{1});}
    private static ShapeRenderer.Output render(String state){return ShapeRenderer.render(data(state),new int[]{0xFFAA7744},"isometric",RenderCamera.defaults("isometric"),16);}
    @Test void deterministic(){assertArrayEquals(render("minecraft:stone").image().pixels(),render("minecraft:stone").image().pixels());}
    @Test void slabsStairsAndCubesDiffer(){assertFalse(Arrays.equals(render("minecraft:stone").image().pixels(),render("minecraft:stone_slab[type=bottom]").image().pixels()));assertFalse(Arrays.equals(render("minecraft:stone_slab[type=bottom]").image().pixels(),render("minecraft:oak_stairs[facing=north]").image().pixels()));}
    @Test void cameraAzimuthChangesOrientation(){var d=data("minecraft:oak_stairs[facing=north]");var a=ShapeRenderer.render(d,new int[]{0xFFAA7744},"isometric",new RenderCamera(45,35,50),16);var b=ShapeRenderer.render(d,new int[]{0xFFAA7744},"isometric",new RenderCamera(135,35,50),16);assertFalse(Arrays.equals(a.image().pixels(),b.image().pixels()));}
    @Test void perspectiveAndOrthographicAreDistinct(){var d=data("minecraft:stone");var a=ShapeRenderer.render(d,new int[]{0xFFAA7744},"isometric",new RenderCamera(135,30,50),16);var b=ShapeRenderer.render(d,new int[]{0xFFAA7744},"perspective",new RenderCamera(135,30,50),16);assertFalse(Arrays.equals(a.image().pixels(),b.image().pixels()));assertEquals("perspective",b.details().get("projection").getAsString());}
    @Test void largeWorldTranslationDoesNotChangePixels(){var d=data("minecraft:oak_stairs[facing=east]");var shifted=new RegionData(new Region(29000000,100,-29000000,29000000,100,-29000000),d.palette(),d.runIndex(),d.runLength());assertArrayEquals(render("minecraft:oak_stairs[facing=east]").image().pixels(),ShapeRenderer.render(shifted,new int[]{0xFFAA7744},"isometric",RenderCamera.defaults("isometric"),16).image().pixels());}
    @Test void transparencyShowsDifferentResultFromOpaqueCube(){assertFalse(Arrays.equals(render("minecraft:stone").image().pixels(),render("minecraft:glass").image().pixels()));}
    @Test void airIsNotGrayFallback(){var air=ShapeRenderer.render(data("minecraft:air"),new int[]{0},"isometric",RenderCamera.defaults("isometric"),16);assertTrue(air.image().legend().isEmpty());assertTrue(air.details().getAsJsonArray("colorFallbackSamples").isEmpty());}
    @Test void missingMapColorsAndModelsAreReported(){var a=ShapeRenderer.render(data("minecraft:glass"),new int[]{0},"isometric",RenderCamera.defaults("isometric"),16);assertEquals(1,a.details().getAsJsonArray("colorFallbackSamples").size());assertEquals(1,render("minecraft:anvil").details().get("cubeFallbackStates").getAsInt());}
    @Test void clippedOpaqueDepthHidesFarCube(){var r=new RegionData(new Region(0,0,0,0,0,1),List.of("minecraft:stone","minecraft:gold_block"),new int[]{0,1},new int[]{1,1});var o=ShapeRenderer.render(r,new int[]{0xFF777777,0xFFFFCC11},"isometric",new RenderCamera(0,5,50),16);assertTrue(o.image().legend().getFirst().block().equals("minecraft:stone"));}
    @Test void budgetReducesRatherThanTruncatesScene(){var d=new RegionData(new Region(0,0,0,99,9,99),List.of("minecraft:stone"),new int[]{0},new int[]{100000});var o=ShapeRenderer.render(d,new int[]{0xFF777777},"isometric",RenderCamera.defaults("isometric"),16);assertTrue(o.details().get("resolutionReduced").getAsBoolean());assertTrue(o.details().get("estimatedIntersectionWork").getAsLong()<=64000000);assertTrue((long)o.image().width()*o.image().height()<=1000000);}
    @Test void impossibleLongSceneRejectsAtMinimumScale(){var d=new RegionData(new Region(0,0,0,199999,0,0),List.of("minecraft:stone"),new int[]{0},new int[]{200000});assertThrows(IllegalArgumentException.class,() -> ShapeRenderer.render(d,new int[]{0xFF777777},"isometric",RenderCamera.defaults("isometric"),1));}
    @Test void transparentLayerCapsAreExplicit(){var d=new RegionData(new Region(0,0,0,0,1,19),List.of("minecraft:glass"),new int[]{0},new int[]{40});var o=ShapeRenderer.render(d,new int[]{0xFFB4DBE8},"isometric",new RenderCamera(0,5,50),16);assertTrue(o.details().get("transparentRaysCapped").getAsInt()>0);assertEquals(8,o.details().get("transparentLayerLimit").getAsInt());}
    @Test void rawRpcBoundsRejectInvalidCoordinatesAndIntegerControls(){for(String s:List.of("{\"from\":[0,0],\"to\":[1,1]}","{\"from\":[0.5,0,0],\"to\":[1,1,1]}","{\"from\":[2147483648,0,0],\"to\":[1,1,1]}","{\"from\":[0,0,0],\"to\":[1,1,1],\"scale\":1.5}","{\"from\":[0,0,0],\"to\":[1,1,1],\"grid\":1}"))assertThrows(IllegalArgumentException.class,() -> RenderCamera.validateBounds(JsonParser.parseString(s).getAsJsonObject(),"isometric"));}
    @Test void invalidEncodingAndViewsReject(){assertThrows(IllegalArgumentException.class,() -> ShapeRenderer.render(data("minecraft:stone"),new int[]{1},"top",RenderCamera.defaults("isometric"),16));var d=new RegionData(new Region(0,0,0,0,0,0),List.of("minecraft:stone"),new int[]{0},new int[]{2});assertThrows(IllegalArgumentException.class,() -> ShapeRenderer.render(d,new int[]{1},"isometric",RenderCamera.defaults("isometric"),16));}
    @Test void cameraRejectsNonNumericInfiniteAndFlatFields(){for(String s:List.of("{\"camera\":{\"azimuth\":360}}","{\"camera\":{\"elevation\":0}}","{\"camera\":{\"fov\":10}}","{\"camera\":{\"azimuth\":\"45\"}}","{\"camera\":{\"unknown\":1}}"))assertThrows(IllegalArgumentException.class,() -> RenderCamera.parse(JsonParser.parseString(s).getAsJsonObject(),"perspective"));assertThrows(IllegalArgumentException.class,() -> new RenderCamera(Double.NaN,30,50));assertThrows(IllegalArgumentException.class,() -> RenderCamera.parse(JsonParser.parseString("{\"camera\":{}}").getAsJsonObject(),"top"));assertThrows(IllegalArgumentException.class,() -> RenderCamera.parse(JsonParser.parseString("{\"camera\":{\"fov\":50}}").getAsJsonObject(),"isometric"));}
}
