// SPDX-License-Identifier: AGPL-3.0-or-later
package cc.wujm.ashlar.tool.mc;

import cc.wujm.ashlar.engine.RegionData;
import com.google.gson.JsonParser;
import org.junit.jupiter.api.Test;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Function;
import static org.junit.jupiter.api.Assertions.*;

class TerrainFitterTest {
    private record P(int x,int y,int z) {}
    private static TerrainFitter.Request request(String extra) {return TerrainFitter.parse(JsonParser.parseString("{\"from\":[0,0],\"to\":[4,4],\"floorY\":10,\"maxDepth\":8"+extra+"}").getAsJsonObject());}
    private static RegionData capture(TerrainFitter.Request r,Function<P,String> state) {var b=r.readBounds();var enc=new RegionData.Encoder();for(int y=b.minY();y<=b.maxY();y++)for(int z=b.minZ();z<=b.maxZ();z++)for(int x=b.minX();x<=b.maxX();x++)enc.add(state.apply(new P(x,y,z)));return enc.finish(b);}
    private static RegionData flat(TerrainFitter.Request r,int height) {return capture(r,p->p.y<=height?"minecraft:stone":"minecraft:air");}
    private static Map<P,String> emitted(TerrainFitter.Request r,TerrainFitter.Output out) {
        Map<P,String> all=new HashMap<>();for(var entry:out.document().getAsJsonObject("components").getAsJsonObject("foundation").getAsJsonArray("fills")) {
            var f=entry.getAsJsonObject();assertTrue(f.get("filter").getAsString().endsWith("air"));var a=f.getAsJsonArray("from");var b=f.getAsJsonArray("to");
            for(int x=a.get(0).getAsInt();x<=b.get(0).getAsInt();x++)for(int y=a.get(1).getAsInt();y<=b.get(1).getAsInt();y++)for(int z=a.get(2).getAsInt();z<=b.get(2).getAsInt();z++)assertNull(all.put(new P(x+r.x0(),y+r.floorY(),z+r.z0()),f.get("block").getAsString()));
        }assertEquals(all.size(),out.summary().get("requestedCells").getAsInt());return all;
    }
    @Test void solidFoundationStopsAboveEachSlopeAnchor() {var r=request("");var data=capture(r,p->p.y<=3+p.x?"minecraft:grass_block[snowy=false]":"minecraft:air");var out=TerrainFitter.fit(r,data);var all=emitted(r,out);for(int x=0;x<5;x++){assertFalse(all.containsKey(new P(x,3+x,2)));assertEquals("$full",all.get(new P(x,4+x,2)));assertEquals("$full",all.get(new P(x,9,2)));}assertEquals(25,out.summary().get("supportColumns").getAsInt());}
    @Test void pierGridIncludesFarEdgesAndAFullDeck() {var r=request(",\"mode\":\"piers\",\"spacing\":3");var all=emitted(r,TerrainFitter.fit(r,flat(r,4)));assertEquals(9,TerrainFitter.fit(r,flat(r,4)).summary().get("supportColumns").getAsInt());assertEquals("$full",all.get(new P(4,5,4)));assertNull(all.get(new P(1,5,1)));for(int x=0;x<5;x++)for(int z=0;z<5;z++)assertEquals("$full",all.get(new P(x,9,z)));}
    @Test void piersMaySpanUnsampledInteriorVoidButMustAnchorSupports() {var r=request(",\"mode\":\"piers\",\"spacing\":4");var data=capture(r,p->p.y<=4&&(p.x==0||p.x==4)&&(p.z==0||p.z==4)?"minecraft:stone":"minecraft:air");assertDoesNotThrow(()->TerrainFitter.fit(r,data));}
    @Test void entranceDescendsToFilledLevelLandingInAllDirections() {for(String facing:new String[]{"north","south","east","west"}){var r=request(",\"entrance\":{\"facing\":\""+facing+"\",\"width\":1,\"maxRun\":8}");var out=TerrainFitter.fit(r,flat(r,5));var all=emitted(r,out);assertEquals(5,out.summary().get("entranceRows").getAsInt());long stairs=all.values().stream().filter(s->s.startsWith("$stairs")).count();assertEquals(4,stairs);assertTrue(all.values().stream().anyMatch(s->s.contains("facing="+(facing.equals("north")?"south":facing.equals("south")?"north":facing.equals("east")?"west":"east"))));}}
    @Test void unevenEntryLanesGetASingleLevelLanding() {var r=request(",\"entrance\":{\"width\":3,\"maxRun\":8}");var data=capture(r,p->p.y<=(p.x==1?5:4)?"minecraft:stone":"minecraft:air");var all=emitted(r,TerrainFitter.fit(r,data));assertNull(all.get(new P(1,5,9)));assertEquals("$full",all.get(new P(2,5,9)));assertEquals("$full",all.get(new P(3,5,9)));}
    @Test void uphillEntranceAndTooShortRunReject() {var r=request(",\"entrance\":{\"width\":1,\"maxRun\":2}");assertThrows(RuntimeException.class,()->TerrainFitter.fit(r,flat(r,3)));var slope=capture(r,p->p.y<=(p.z>4?10:4)?"minecraft:stone":"minecraft:air");assertThrows(RuntimeException.class,()->TerrainFitter.fit(r,slope));}
    @Test void capturedCellsAreNeverMutated() {var r=request("");var data=flat(r,4);var before=data.toJson();TerrainFitter.fit(r,data);assertEquals(before,data.toJson());}
    @Test void protectedPlantsLiquidsGravityAndUnknownAnchorsReject() {for(String s:new String[]{"minecraft:water[level=0]","minecraft:lava[level=0]","minecraft:chest[facing=north]","minecraft:oak_log[axis=y]","minecraft:oak_leaves[persistent=true]","minecraft:sand","minecraft:gravel","minecraft:short_grass","minecraft:stone_bricks"}){var r=request("");var data=capture(r,p->p.y==5?s:p.y<5?"minecraft:stone":"minecraft:air");assertThrows(RuntimeException.class,()->TerrainFitter.fit(r,data),s);}}
    @Test void deckOrHeadroomObstructionsRejectWithoutOutput() {for(int y:new int[]{9,10,11}){var r=request("");var data=capture(r,p->p.x==2&&p.z==2&&p.y==y?"minecraft:chest":p.y<=4?"minecraft:stone":"minecraft:air");assertThrows(RuntimeException.class,()->TerrainFitter.fit(r,data));}}
    @Test void emptyCliffAndTooDeepAnchorsReject() {var r=request("");assertThrows(RuntimeException.class,()->TerrainFitter.fit(r,capture(r,p->"minecraft:air")));assertThrows(RuntimeException.class,()->TerrainFitter.fit(r,flat(r,0)));}
    @Test void existingNaturalDeckPlaneIsPreserved() {var r=request("");var out=TerrainFitter.fit(r,capture(r,p->p.y<=(p.x==0?9:5)?"minecraft:stone":"minecraft:air"));var all=emitted(r,out);assertNull(all.get(new P(0,9,0)));assertEquals("$full",all.get(new P(1,9,0)));}
    @Test void airVariantsHaveExactMatchingFilters() {var r=request("");var out=TerrainFitter.fit(r,capture(r,p->p.y<=4?"minecraft:stone":p.y==6?"minecraft:cave_air":p.y==7?"minecraft:void_air":"minecraft:air"));var filters=new java.util.HashSet<String>();for(var f:out.document().getAsJsonObject("components").getAsJsonObject("foundation").getAsJsonArray("fills"))filters.add(f.getAsJsonObject().get("filter").getAsString());assertEquals(java.util.Set.of("minecraft:air","minecraft:cave_air","minecraft:void_air"),filters);}
    @Test void alreadyCompleteNaturalPlaneRejectsEmptyDocument() {var r=request("");assertThrows(RuntimeException.class,()->TerrainFitter.fit(r,flat(r,9)));}
    @Test void localNegativeOffsetsMapBackToOriginalWorldCoordinates() {var json=JsonParser.parseString("{\"from\":[120,-80],\"to\":[124,-76],\"floorY\":10,\"maxDepth\":8,\"entrance\":{\"facing\":\"north\",\"maxRun\":8}}").getAsJsonObject();var r=TerrainFitter.parse(json);var out=TerrainFitter.fit(r,flat(r,5));assertEquals("[120,10,-80]",out.summary().get("origin").toString());assertTrue(out.document().toString().contains("-1"));BlueprintCompiler.validate(out.document());var request=JsonParser.parseString("{\"blueprint\":{\"id\":\"site\"},\"transform\":{\"origin\":[120,10,-80]}}").getAsJsonObject();assertEquals(1,BlueprintCompiler.compile(out.document(),request,BlueprintCompiler.Limits.DEFAULT).size());}
    @Test void readEnvelopeIncludesHeadroomDepthAndAllEntryDirections() {for(String facing:new String[]{"north","south","east","west"}){var r=request(",\"entrance\":{\"facing\":\""+facing+"\",\"maxRun\":8}");assertEquals(1,r.readBounds().minY());assertEquals(11,r.readBounds().maxY());assertEquals(5*13*11,r.readBounds().volume());}}
    @Test void malformedFractionalOverflowUnknownAndInapplicableFieldsReject() {for(String json:new String[]{"{}","{\"from\":[0.5,0],\"to\":[1,1],\"floorY\":10}","{\"from\":[0,0],\"to\":[64,1],\"floorY\":10}","{\"from\":[0,0],\"to\":[1,1],\"floorY\":2147483647}","{\"from\":[0,0],\"to\":[1,1],\"floorY\":-2147483648}","{\"from\":[0,0],\"to\":[1,1],\"floorY\":10,\"spacing\":4}","{\"from\":[0,0],\"to\":[1,1],\"floorY\":10,\"unknown\":1}","{\"from\":[0,0],\"to\":[1,1],\"floorY\":10,\"entrance\":{\"width\":3}}"})assertThrows(RuntimeException.class,()->TerrainFitter.parse(JsonParser.parseString(json).getAsJsonObject()));}
    @Test void oversizedCaptureAndEdgeExpansionRejectBeforeAllocation() {assertThrows(RuntimeException.class,()->TerrainFitter.parse(JsonParser.parseString("{\"from\":[0,0],\"to\":[63,63],\"floorY\":100,\"maxDepth\":64}").getAsJsonObject()));assertThrows(RuntimeException.class,()->TerrainFitter.parse(JsonParser.parseString("{\"from\":[29999998,0],\"to\":[29999999,2],\"floorY\":10,\"entrance\":{\"facing\":\"east\"}}").getAsJsonObject()));}
    @Test void flatSupportsCompressWithoutChangingRequestedCells() {var r=request("");var out=TerrainFitter.fit(r,flat(r,4));assertEquals(5,out.summary().get("operations").getAsInt());assertEquals(125,emitted(r,out).size());}
    @Test void wrongCaptureBoundsReject() {var r=request("");var other=request(",\"mode\":\"piers\"");var data=flat(other,4);var fake=new RegionData(new cc.wujm.ashlar.engine.Region(0,0,0,0,0,0),data.palette(),new int[]{0},new int[]{1});assertThrows(RuntimeException.class,()->TerrainFitter.fit(r,fake));}
}
