// SPDX-License-Identifier: AGPL-3.0-or-later
package cc.wujm.ashlar.tool;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * All registered {@code /tools/&lt;name&gt;.json} resources (generated by {@code
 * mcp-server/tools/export-specs.mjs}) load, in the same order as {@code
 * mcp-server/src/tools/index.ts}'s {@code registerAllTools}, and each description carries the
 * four-part structure (spec section 4.3 part 4: what / when to use and not / parameters or
 * coordinates / side effects).
 */
class ToolSpecTest {

    /** Same order as mcp-server/src/tools/index.ts's registerAllTools and ToolRegistry's registration in AshlarPlugin. */
    private static final List<String> EXPECTED_ORDER = List.of(
            "mc_status", "mc_players", "mc_survey", "mc_build", "mc_blueprint", "mc_plan", "mc_verify", "mc_repair", "mc_inspect", "mc_diff", "mc_render", "mc_sightline", "mc_snapshot", "mc_restore", "mc_protect", "mc_command");

    @Test
    void everyToolSpecLoadsWithMatchingName() {
        for (String name : EXPECTED_ORDER) {
            ToolSpec spec = ToolSpec.load(name);
            assertEquals(name, spec.name());
            assertFalse(spec.title().isBlank(), name + ": title must not be blank");
            assertFalse(spec.description().isBlank(), name + ": description must not be blank");
        }
    }

    @Test
    void everyDescriptionHasTheFourSectionMarkers() {
        for (String name : EXPECTED_ORDER) {
            ToolSpec spec = ToolSpec.load(name);
            String d = spec.description();
            assertTrue(d.contains("WHEN TO USE:"), name + ": missing WHEN TO USE section");
            assertTrue(d.contains("WHEN NOT TO USE:"), name + ": missing WHEN NOT TO USE section");
            assertTrue(d.contains("PARAMETERS:") || d.contains("COORDINATES:"), name + ": missing PARAMETERS/COORDINATES section");
            assertTrue(d.contains("SIDE EFFECTS:"), name + ": missing SIDE EFFECTS section");
        }
    }

    @Test
    void inputSchemaAndAnnotationsAreObjects() {
        for (String name : EXPECTED_ORDER) {
            ToolSpec spec = ToolSpec.load(name);
            assertTrue(spec.inputSchema().has("type"), name + ": inputSchema missing \"type\"");
            assertTrue(spec.annotations().has("readOnlyHint"), name + ": annotations missing \"readOnlyHint\"");
        }
    }

    @Test
    void defaultInstructionsKeepVerificationLightweight() {
        String instructions = new ToolRegistry(List.of()).instructions();
        assertTrue(instructions.contains("Default lightweight workflow:"));
        assertTrue(instructions.contains("one mc_survey"));
        assertTrue(instructions.contains("one mc_render"));
        assertTrue(instructions.contains("Full exact verification is opt-in"));
        assertTrue(instructions.contains("mandatory plugin-side structural safety validation"));
        assertTrue(instructions.contains("Preserve rollback protection"));
        assertFalse(instructions.contains("Before nontrivial builds, run mc_plan"));
        assertTrue(instructions.contains("Sixteen tools"));
    }

    @Test
    void buildReportAndOrderingGuidanceAreExplicit() {
        var spec = ToolSpec.load("mc_build");
        var detailed = spec.inputSchema().getAsJsonObject("properties").getAsJsonObject("detailed");
        assertEquals("boolean", detailed.get("type").getAsString());
        assertFalse(detailed.get("default").getAsBoolean());
        assertTrue(spec.description().contains("ALWAYS fills -> text -> blocks"));
        assertTrue(spec.description().contains("final minecraft:air entries"));
        String instructions = new ToolRegistry(List.of()).instructions();
        assertTrue(instructions.contains("not sign text or container inventories"));
        assertTrue(instructions.contains("failed check is not permission to delete"));
    }

    @Test
    void photoWorkflowSeparatesEvidenceFromBlockAuditing() {
        String instructions = new ToolRegistry(List.of()).instructions();
        assertTrue(instructions.contains("Photo-reference reconstruction:"));
        assertTrue(instructions.contains("observed features from inferred geometry and unknown/hidden areas"));
        assertTrue(instructions.contains("does not automatically request exact block-state auditing"));
        assertTrue(instructions.contains("not with a photograph"));
        assertFalse(instructions.contains("exact verification/fidelity"));
    }

    @Test
    void advancedToolDescriptionsDoNotImplyRoutineVerification() {
        assertTrue(ToolSpec.load("mc_plan").description().contains("optional escalation"));
        assertTrue(ToolSpec.load("mc_verify").description().contains("not for ordinary builds by default"));
        assertTrue(ToolSpec.load("mc_repair").description().contains("opt-in exact-verification workflow"));
    }

    @Test
    void renderAndPlanExposeMatchingAngledCameraSchemas() {
        var render=ToolSpec.load("mc_render").inputSchema().getAsJsonObject("properties");
        var preview=ToolSpec.load("mc_plan").inputSchema().getAsJsonObject("properties").getAsJsonObject("preview").getAsJsonObject("properties");
        assertEquals(render.get("camera"),preview.get("camera"));
        for(var p:List.of(render,preview)){
            String views=p.getAsJsonObject("view").getAsJsonArray("enum").toString();
            assertTrue(views.contains("isometric"));assertTrue(views.contains("perspective"));
            assertEquals(360,p.getAsJsonObject("camera").getAsJsonObject("properties").getAsJsonObject("azimuth").get("exclusiveMaximum").getAsInt());
        }
        String instructions=new ToolRegistry(List.of()).instructions();
        assertTrue(instructions.contains("schematic visual cuboids"));
        assertFalse(instructions.contains("not shape-aware perspective views"));
    }

    @Test
    void generatorsRemainAnOptionalBlueprintAction() {
        var spec=ToolSpec.load("mc_blueprint");
        assertTrue(spec.inputSchema().getAsJsonObject("properties").getAsJsonObject("action").get("enum").toString().contains("generate"));
        assertEquals(4,spec.inputSchema().getAsJsonObject("properties").getAsJsonObject("generator").getAsJsonArray("oneOf").size());
        assertTrue(spec.description().contains("never clears"));
        assertTrue(spec.description().contains("before saving"));
        assertTrue(new ToolRegistry(List.of()).instructions().contains("Default lightweight workflow:"));
    }

    @Test
    void terrainFitIsOptionalAndRequiresAnExplicitWalkingPlane() {
        var spec=ToolSpec.load("mc_blueprint");var props=spec.inputSchema().getAsJsonObject("properties");
        assertTrue(props.getAsJsonObject("action").get("enum").toString().contains("fit"));
        assertTrue(props.getAsJsonObject("site").get("required").toString().contains("floorY"));
        assertTrue(spec.description().contains("not a mandatory check"));
        assertTrue(spec.description().contains("site-specific"));
        assertTrue(new ToolRegistry(List.of()).instructions().contains("one mc_render"));
    }

    @Test
    void toJsonRoundTripsTheSameFields() {
        ToolSpec spec = ToolSpec.load("mc_status");
        var json = spec.toJson();
        assertEquals(spec.name(), json.get("name").getAsString());
        assertEquals(spec.title(), json.get("title").getAsString());
        assertEquals(spec.description(), json.get("description").getAsString());
    }
}
